Use MiniLZO v2.10
KallistiOS/dcload-serial pull request #12
Opened 2023-04-12 20:05 UTC by Octoate

I updated the source to use the version 2.10 of MiniLZO instead of v1.06. It features speed and portability improvements. The version was tested under Windows and Linux with the examples of KallistOS. The newly compiled version is also backward compatible with previous versions.
I also increased the version number of dctool-serial to v1.1.0.

2023-06-06 02:18 UTC, ljsebald requested changes
My apologies for how long it took to get this PR reviewed. I'd be happy to accept it, except for changing the version number. If you don't mind reverting the changes to the program's version number, then I'll be happy to merge this PR.

Thanks for your contribution!

2023-06-15 20:15 UTC, andressbarajas requested changes

2023-06-15 20:15 UTC, andressbarajas commented on Makefile.cfg
> +VERSION = 1.1.0
```suggestion
VERSION = 1.0.6
```

2023-06-15 20:15 UTC, andressbarajas commented on README.md
> +# dcload-serial 1.1.0
```suggestion
# dcload-serial 1.0.6
```

2023-06-18 07:55 UTC, Octoate commented
Hi,
thanks for having a look at the PR. It took a bit from my side as well, so absolutely no problem :-). The version change was indeed for testing my version and it absolutely makes sense to not change it.
I hope that the PR is okay now.

@andressbarajas Thanks for your suggestion 👍

2023-06-18 14:01 UTC, ljsebald approved these changes

2023-06-18 14:02 UTC, merged